// packages/vue/src/lib/core/input/cad-input.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue';
import '@cad/core'; // Register the web component

withDefaults(
  defineProps<{
    modelValue?: string;
    placeholder?: string;
    type?: string;
    disabled?: boolean;
  }>(),
  {
    modelValue: '',
    placeholder: '',
    type: 'text',
    disabled: false,
  },
);

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void;
}>();

const cadInputRef = ref<HTMLElement | null>(null);

const handleInput = (event: Event) => {
  const customEvent = event as CustomEvent;
  emit('update:modelValue', customEvent.detail.value);
};

onMounted(() => {
  if (cadInputRef.value) {
    cadInputRef.value.addEventListener('cad-input', handleInput);
  }
});

onBeforeUnmount(() => {
  if (cadInputRef.value) {
    cadInputRef.value.removeEventListener('cad-input', handleInput);
  }
});
</script>

<template>
  <cad-input
    ref="cadInputRef"
    :value="modelValue"
    :placeholder="placeholder"
    :type="type"
    :disabled="disabled"
  >
  </cad-input>
</template>

// packages/react/src/lib/core/input/cad-input.tsx
import React, {  useEffect, useRef } from 'react';
import '@cad/core';
import { CadInputProps } from '../../model/cad-input.model';

export const CadInput: React.FC<CadInputProps> = ({
  value,
  placeholder,
  type = 'text',
  disabled,
  onValueChange,
  ...rest
}) => {
  const ref = useRef<HTMLElement>(null);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    const handleInput = (e: Event) => {
      const customEvent = e as CustomEvent;
      if (onValueChange) {
        onValueChange(customEvent.detail.value);
      }
    };

    el.addEventListener('cad-input', handleInput);
    return () => {
      el.removeEventListener('cad-input', handleInput);
    };
  }, [onValueChange]);

  return (
    <cad-input
      ref={ref}
      value={value}
      placeholder={placeholder}
      type={type}
      disabled={disabled ? true : undefined}
      {...rest}
    />
  );
};
