// packages/vue/src/lib/core/accordion/cad-accordion.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue';
import '@cad/core'; // Register the web component

withDefaults(
  defineProps<{
    multiple?: boolean;
    headingLevel?: number;
  }>(),
  {
    multiple: false,
    headingLevel: 3,
  },
);

const emit = defineEmits<{
  (e: 'item-toggle', name: string, expanded: boolean): void;
}>();

const cadAccordionRef = ref<HTMLElement | null>(null);

const handleChange = (event: Event) => {
  const customEvent = event as CustomEvent<{ name: string; expanded: boolean }>;
  emit('item-toggle', customEvent.detail.name, customEvent.detail.expanded);
};

onMounted(() => {
  if (cadAccordionRef.value) {
    cadAccordionRef.value.addEventListener('cad-accordion-change', handleChange);
  }
});

onBeforeUnmount(() => {
  if (cadAccordionRef.value) {
    cadAccordionRef.value.removeEventListener('cad-accordion-change', handleChange);
  }
});
</script>

<template>
  <cad-accordion
    ref="cadAccordionRef"
    :multiple="multiple"
    :heading-level="headingLevel"
  >
    <slot></slot>
  </cad-accordion>
</template>

// packages/react/src/lib/core/accordion/cad-accordion.tsx
import React, { useEffect, useRef } from 'react';
import '@cad/core';
import { CadAccordionProps, CadAccordionItemProps } from '../../model/cad-accordion.model';

export const CadAccordion: React.FC<CadAccordionProps> = ({
  children,
  multiple,
  headingLevel,
  onItemToggle,
  ...rest
}) => {
  const ref = useRef<HTMLElement>(null);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    const handleChange = (e: Event) => {
      const customEvent = e as CustomEvent<{ name: string; expanded: boolean }>;
      if (onItemToggle) {
        onItemToggle(customEvent.detail.name, customEvent.detail.expanded);
      }
    };

    el.addEventListener('cad-accordion-change', handleChange);
    return () => {
      el.removeEventListener('cad-accordion-change', handleChange);
    };
  }, [onItemToggle]);

  return (
    <cad-accordion
      ref={ref}
      multiple={multiple ? true : undefined}
      heading-level={headingLevel}
      {...rest}
    >
      {children}
    </cad-accordion>
  );
};

export const CadAccordionItem: React.FC<CadAccordionItemProps> = ({
  children,
  name,
  expanded,
  disabled,
  ...rest
}) => {
  return (
    <cad-accordion-item
      name={name}
      expanded={expanded ? true : undefined}
      disabled={disabled ? true : undefined}
      {...rest}
    >
      {children}
    </cad-accordion-item>
  );
};
