// apps/vue-tester/src/app/App.vue
<script setup lang="ts">
import { CadButton, CadInput } from '@cad/vue';
</script>

<template>
  <div style="padding: 20px">
    <h1>Vue Test App</h1>
    <cad-button variant="primary">Click Me</cad-button>
    <br><br>
    <cad-input placeholder="Type something..." type="text"></cad-input>
  </div>
</template>

// apps/react-tester/src/app/app.tsx
import { CadButton, CadInput } from '@cad/react';

export function App() {
  return (
    <div style={{ padding: '20px' }}>
      <h1>React Test App</h1>
      <CadButton variant="primary">Click Me</CadButton>
      <br /><br />
      <CadInput placeholder="Type something..." type="text" />
    </div>
  );
}

export default App;
