// packages/vue/src/lib/core/tabs/cad-tab.vue
<script setup lang="ts">
import '@cad/core'; // Register the web component

withDefaults(
  defineProps<{
    panel?: string;
    disabled?: boolean;
  }>(),
  {
    panel: '',
    disabled: false,
  },
);
</script>

<template>
  <cad-tab :panel="panel" :disabled="disabled">
    <slot></slot>
  </cad-tab>
</template>

// packages/angular/src/lib/cad-tab.component.ts
import { Component, input, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import '@cad/core';

@Component({
  selector: 'cad-ui-angular-tab',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <cad-tab [attr.panel]="panel()" [attr.disabled]="disabled() ? '' : null">
      <ng-content></ng-content>
    </cad-tab>
  `,
})
export class CadUiAngularTabComponent {
  panel = input<string>('');
  disabled = input<boolean>(false);
}
