// packages/vue/src/lib/cad-input.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue';
import '@cad/core'; // Register the web component

const props = withDefaults(
  defineProps<{
    modelValue?: string;
    placeholder?: string;
    type?: string;
    disabled?: boolean;
  }>(),
  {
    modelValue: '',
    placeholder: '',
    type: 'text',
    disabled: false,
  },
);

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void;
}>();

const cadInputRef = ref<HTMLElement | null>(null);

const handleInput = (event: Event) => {
  const customEvent = event as CustomEvent;
  emit('update:modelValue', customEvent.detail.value);
};

onMounted(() => {
  if (cadInputRef.value) {
    cadInputRef.value.addEventListener('cad-input', handleInput);
  }
});

onBeforeUnmount(() => {
  if (cadInputRef.value) {
    cadInputRef.value.removeEventListener('cad-input', handleInput);
  }
});
</script>

<template>
  <cad-input
    ref="cadInputRef"
    :value="modelValue"
    :placeholder="placeholder"
    :type="type"
    :disabled="disabled ? '' : undefined"
  >
  </cad-input>
</template>

// packages/angular/src/lib/cad-input.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  input,
  output,
  ElementRef,
  ViewChild,
  AfterViewInit,
  OnDestroy,
} from '@angular/core';
import '@cad/core'; // Register the web component

@Component({
  selector: 'cad-ui-angular-input',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <cad-input
      #inputEl
      [attr.value]="value()"
      [attr.placeholder]="placeholder()"
      [attr.type]="type()"
      [attr.disabled]="disabled() ? '' : null"
    >
    </cad-input>
  `,
})
export class CadUiAngularInputComponent implements AfterViewInit, OnDestroy {
  value = input<string>('');
  placeholder = input<string>('');
  type = input<string>('text');
  disabled = input<boolean>(false);

  valueChange = output<string>();

  @ViewChild('inputEl') inputEl!: ElementRef<HTMLElement>;

  private handleInput = (event: Event) => {
    const customEvent = event as CustomEvent;
    this.valueChange.emit(customEvent.detail.value);
  };

  ngAfterViewInit() {
    if (this.inputEl) {
      this.inputEl.nativeElement.addEventListener(
        'cad-input',
        this.handleInput,
      );
    }
  }

  ngOnDestroy() {
    if (this.inputEl) {
      this.inputEl.nativeElement.removeEventListener(
        'cad-input',
        this.handleInput,
      );
    }
  }
}
