// packages/angular/src/lib/cad-button.component.ts
import { Component, input, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import '@cad/core';

@Component({
  selector: 'cad-ui-angular-button',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <cad-button [attr.variant]="variant" [attr.disabled]="disabled ? '' : null">
      <ng-content></ng-content>
    </cad-button>
  `,
})
export class CadUiAngularButtonComponent {
  variant = input<'primary' | 'secondary' | 'danger'>('primary');
  disabled = input<boolean>(false);
}

// packages/vue/src/lib/core/button/cad-button.vue
<script setup lang="ts">
import '@cad/core'; // Register the web component

withDefaults(
  defineProps<{
    variant?: 'primary' | 'secondary' | 'danger';
    disabled?: boolean;
  }>(),
  {
    variant: 'primary',
    disabled: false,
  },
);
</script>

<template>
  <cad-button :variant="variant" :disabled="disabled">
    <slot></slot>
  </cad-button>
</template>
