// packages/angular/src/lib/core/accordion/cad-accordion-item.component.ts
import { Component, input, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import '@cad/core';

@Component({
  selector: 'cad-ui-angular-accordion-item',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <cad-accordion-item
      [attr.name]="name()"
      [attr.expanded]="expanded() ? '' : null"
      [attr.disabled]="disabled() ? '' : null"
    >
      <ng-content select="[slot=heading]"></ng-content>
      <ng-content></ng-content>
    </cad-accordion-item>
  `,
})
export class CadUiAngularAccordionItemComponent {
  name = input<string>('');
  expanded = input<boolean>(false);
  disabled = input<boolean>(false);
}

// packages/vue/src/lib/core/accordion/cad-accordion-item.vue
<script setup lang="ts">
import '@cad/core'; // Register the web component

withDefaults(
  defineProps<{
    name?: string;
    expanded?: boolean;
    disabled?: boolean;
  }>(),
  {
    name: '',
    expanded: false,
    disabled: false,
  },
);
</script>

<template>
  <cad-accordion-item :name="name" :expanded="expanded" :disabled="disabled">
    <div slot="heading"><slot name="heading"></slot></div>
    <slot></slot>
  </cad-accordion-item>
</template>
